#!/usr/bin/env bash
#
# kernel-downgrade.sh — Unattended downgrade to 6.8.0-88 and set as GRUB default
#
# Writes state to /var/lib/kernel-migration/state.env for the revert script.
# Exit codes: 0 = success, non-zero = failure

set -euo pipefail

TARGET_VERSION="6.8.0-88"
TARGET_KERNEL="${TARGET_VERSION}-generic"
GRUB_DEFAULT_FILE="/etc/default/grub"
STATE_DIR="/var/lib/kernel-migration"
STATE_FILE="${STATE_DIR}/state.env"
LOG_FILE="/var/log/kernel-downgrade.log"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
GRUB_BACKUP="${GRUB_DEFAULT_FILE}.premigration-${TIMESTAMP}"

exec > >(tee -a "$LOG_FILE") 2>&1

log()  { echo "[$(date '+%F %T')] [*] $*"; }
err()  { echo "[$(date '+%F %T')] [✗] $*" >&2; }

if [[ -d "${STATE_DIR}" ]] ; then
  err "This process should only be ran once.  Remove ${STATE_DIR} if you seriously want to rerun."
  exit 1
fi

CODENAME=`lsb_release -cs`
if [[ "${CODENAME}" != "noble" ]] ; then
  err "Only runs on ubuntu noble"
  exit 1
fi

running=$(uname -r)
if [[ "${running}" == "${TARGET_KERNEL}" ]] ; then
  err "Already on correct kernel."
  exit 1
fi

latest=$(dpkg --list 'linux-image-[0-9]*' 2>/dev/null \
    | awk '/^ii/ {print $2}' \
    | sed 's/^linux-image-//' \
    | sort -V \
    | tail -n1)

if [[ "$running" == "$latest" ]]; then
    log "OK: Running the latest installed kernel ($running)"
else
    err "REBOOT NEEDED: Running $running, but $latest is installed"
    exit 1
fi

if [[ $EUID -ne 0 ]]; then
    err "Must run as root."
    exit 1
fi

log "Starting kernel downgrade to ${TARGET_KERNEL}"
log "Current running kernel: $(uname -r)"

mkdir -p "$STATE_DIR"

# Record pre-migration state
PREVIOUS_KERNEL="$(uname -r)"
PREVIOUS_HOLDS="$(apt-mark showhold | tr '\n' ' ')"

# Capture current GRUB_DEFAULT value (if any) for restoration
PREVIOUS_GRUB_DEFAULT="$(grep -E '^\s*GRUB_DEFAULT=' "$GRUB_DEFAULT_FILE" || true)"

# Track whether we installed the kernel (so revert knows whether to remove it)
KERNEL_WAS_INSTALLED_BY_US="false"

# Short-circuit if already on target
if [[ "$(uname -r)" == "${TARGET_KERNEL}" ]]; then
    log "Already running ${TARGET_KERNEL}. Recording state and exiting."
    cat > "$STATE_FILE" <<EOF
# Generated by kernel-downgrade.sh at ${TIMESTAMP}
PREVIOUS_KERNEL="${PREVIOUS_KERNEL}"
TARGET_KERNEL="${TARGET_KERNEL}"
KERNEL_WAS_INSTALLED_BY_US="false"
GRUB_BACKUP=""
PREVIOUS_HOLDS="${PREVIOUS_HOLDS}"
NO_OP="true"
EOF
    exit 0
fi

# 1. Install target kernel if not already present
if dpkg -l "linux-image-${TARGET_KERNEL}" 2>/dev/null | grep -q '^ii'; then
    log "Kernel ${TARGET_KERNEL} already installed."
else
    log "Updating apt cache..."
    DEBIAN_FRONTEND=noninteractive apt-get update -qq

    log "Checking availability of linux-image-${TARGET_KERNEL}..."
    if ! apt-cache show "linux-image-${TARGET_KERNEL}" >/dev/null 2>&1; then
        err "Package linux-image-${TARGET_KERNEL} not available in apt."
        err "Pre-stage .deb files and install before running this script."
        exit 2
    fi

    log "Installing ${TARGET_KERNEL} packages..."
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        -o Dpkg::Options::="--force-confdef" \
        -o Dpkg::Options::="--force-confold" \
        "linux-image-${TARGET_KERNEL}" \
        "linux-headers-${TARGET_KERNEL}" \
        "linux-modules-${TARGET_KERNEL}" \
        "linux-modules-extra-${TARGET_KERNEL}"

    KERNEL_WAS_INSTALLED_BY_US="true"
    log "Kernel packages installed."
fi

# 2. Locate exact GRUB menu entry
GRUB_CFG="/boot/grub/grub.cfg"
if [[ ! -f "$GRUB_CFG" ]]; then
    err "${GRUB_CFG} not found."
    exit 3
fi

SUBMENU="$(grep -oP "submenu '\K[^']+" "$GRUB_CFG" | head -n1 || true)"
ENTRY="$(grep -oP "menuentry '\K[^']+" "$GRUB_CFG" | grep -F "${TARGET_KERNEL}" | grep -v recovery | head -n1 || true)"

if [[ -z "$ENTRY" ]]; then
    err "No GRUB menu entry found for ${TARGET_KERNEL}."
    exit 4
fi

if [[ -n "$SUBMENU" ]]; then
    GRUB_DEFAULT_VALUE="${SUBMENU}>${ENTRY}"
else
    GRUB_DEFAULT_VALUE="${ENTRY}"
fi
log "GRUB entry: ${GRUB_DEFAULT_VALUE}"

# 3. Back up and patch /etc/default/grub
log "Backing up ${GRUB_DEFAULT_FILE} → ${GRUB_BACKUP}"
cp -a "$GRUB_DEFAULT_FILE" "$GRUB_BACKUP"

set_grub_var() {
    local key="$1" value="$2"
    if grep -qE "^\s*${key}=" "$GRUB_DEFAULT_FILE"; then
        sed -i "s|^\s*${key}=.*|${key}=${value}|" "$GRUB_DEFAULT_FILE"
    else
        echo "${key}=${value}" >> "$GRUB_DEFAULT_FILE"
    fi
}

set_grub_var "GRUB_DEFAULT"       "\"${GRUB_DEFAULT_VALUE}\""
set_grub_var "GRUB_SAVEDEFAULT"   "false"
set_grub_var "GRUB_TIMEOUT_STYLE" "menu"
set_grub_var "GRUB_TIMEOUT"       "5"

log "Running update-grub..."
update-grub

# 4. Hold the target kernel so unattended-upgrades can't move it
log "Holding ${TARGET_KERNEL} packages..."
apt-mark hold \
    "linux-image-${TARGET_KERNEL}" \
    "linux-headers-${TARGET_KERNEL}" \
    linux-image-generic \
    linux-headers-generic \
    linux-generic 2>&1 || true

# 5. Write state file for the revert script
log "Writing state file: ${STATE_FILE}"
cat > "$STATE_FILE" <<EOF
# Generated by kernel-downgrade.sh at ${TIMESTAMP}
PREVIOUS_KERNEL="${PREVIOUS_KERNEL}"
TARGET_KERNEL="${TARGET_KERNEL}"
KERNEL_WAS_INSTALLED_BY_US="${KERNEL_WAS_INSTALLED_BY_US}"
GRUB_BACKUP="${GRUB_BACKUP}"
PREVIOUS_HOLDS="${PREVIOUS_HOLDS}"
NO_OP="false"
EOF
chmod 600 "$STATE_FILE"

log "Downgrade complete. Reboot required to activate ${TARGET_KERNEL}."
exit 0
