#!/usr/bin/env bash
set -euo pipefail

# Generate a paste-ready PowerShell script for installing the AWS MGN
# replication agent on a Windows source server.
#
# Required environment variables:
#   AWS_REGION
#   AWS_ACCESS_KEY_ID
#   AWS_SECRET_ACCESS_KEY
#   AWS_SESSION_TOKEN
#
# Optional environment variables:
#   MGN_USER_PROVIDED_ID
#   MGN_ENDPOINT
#   MGN_S3_ENDPOINT
#   MGN_NO_REPLICATION        true/false, 1/0, yes/no
#   MGN_DUALSTACK             true/false, 1/0, yes/no
#   MGN_INSTALLER_DIR         defaults to C:\Temp\AwsMgnAgent
#   MGN_INSTALLER_URL         overrides the standard regional installer URL

required_vars=(
  AWS_REGION
  AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY
  AWS_SESSION_TOKEN
)

missing_vars=()
for var_name in "${required_vars[@]}"; do
  if [[ -z "${!var_name:-}" ]]; then
    missing_vars+=("$var_name")
  fi
done

if ((${#missing_vars[@]} > 0)); then
  printf 'Missing required environment variable(s): %s\n' "${missing_vars[*]}" >&2
  exit 1
fi

ps_sq() {
  local value=${1-}
  value=${value//\'/\'\'}
  printf "'%s'" "$value"
}

is_truthy() {
  case "${1:-}" in
    1|true|TRUE|True|yes|YES|Yes|y|Y|on|ON|On) return 0 ;;
    *) return 1 ;;
  esac
}

aws_region=${AWS_REGION}
installer_dir=${MGN_INSTALLER_DIR:-'C:\Temp\AwsMgnAgent'}
installer_url=${MGN_INSTALLER_URL:-"https://aws-application-migration-service-${aws_region}.s3.${aws_region}.amazonaws.com/latest/windows/AwsReplicationWindowsInstaller.exe"}

cat <<EOF
# Paste into an elevated Windows PowerShell session on the source server.
# Generated by generate_mgn_agent_ps1.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ').
\$ErrorActionPreference = 'Stop'
\$currentIdentity = [Security.Principal.WindowsIdentity]::GetCurrent()
\$principal = [Security.Principal.WindowsPrincipal]::new(\$currentIdentity)
if (-not \$principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    throw 'Run this script from an elevated PowerShell session.'
}
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
\$InstallerDir = $(ps_sq "$installer_dir")
\$InstallerPath = Join-Path \$InstallerDir 'AwsReplicationWindowsInstaller.exe'
\$InstallerUrl = $(ps_sq "$installer_url")
New-Item -Path \$InstallerDir -ItemType Directory -Force | Out-Null
Invoke-WebRequest -Uri \$InstallerUrl -OutFile \$InstallerPath
\$AgentArgs = @(
    '--region', $(ps_sq "$AWS_REGION"),
    '--aws-access-key-id', $(ps_sq "$AWS_ACCESS_KEY_ID"),
    '--aws-secret-access-key', $(ps_sq "$AWS_SECRET_ACCESS_KEY"),
    '--aws-session-token', $(ps_sq "$AWS_SESSION_TOKEN"),
    '--no-prompt'
)
EOF

if [[ -n "${MGN_USER_PROVIDED_ID:-}" ]]; then
  cat <<EOF
\$AgentArgs += @('--user-provided-id', $(ps_sq "$MGN_USER_PROVIDED_ID"))
EOF
fi

if [[ -n "${MGN_ENDPOINT:-}" ]]; then
  cat <<EOF
\$AgentArgs += @('--endpoint', $(ps_sq "$MGN_ENDPOINT"))
EOF
fi

if [[ -n "${MGN_S3_ENDPOINT:-}" ]]; then
  cat <<EOF
\$AgentArgs += @('--s3-endpoint', $(ps_sq "$MGN_S3_ENDPOINT"))
EOF
fi

if is_truthy "${MGN_NO_REPLICATION:-}"; then
  cat <<'EOF'
$AgentArgs += '--no-replication'
EOF
fi

if is_truthy "${MGN_DUALSTACK:-}"; then
  cat <<'EOF'
$AgentArgs += '--dualstack'
EOF
fi

cat <<'EOF'
Write-Host "Downloaded AWS MGN agent installer to $InstallerPath - Launching"
& $InstallerPath @AgentArgs
if ($LASTEXITCODE -ne 0) {
    throw "AWS MGN agent installer exited with code $LASTEXITCODE"
}
EOF
